wandb_version: 1

_n_gpu:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: huggingface
    huggingface_version: 4.3.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      3:
      - 1
      4: 3.8.8
      5: 0.10.21
      6: 4.3.3
      8:
      - 1
      - 5
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
ddp_find_unused_parameters:
  desc: null
  value: None
debug:
  desc: null
  value: false
deepspeed:
  desc: null
  value: None
disable_tqdm:
  desc: null
  value: false
do_eval:
  desc: null
  value: None
do_predict:
  desc: null
  value: false
do_train:
  desc: null
  value: false
eval_accumulation_steps:
  desc: null
  value: None
eval_batch_size:
  desc: null
  value: 32
eval_steps:
  desc: null
  value: 500
evaluation_strategy:
  desc: null
  value: epoch
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_opt_level:
  desc: null
  value: '01'
gradient_accumulation_steps:
  desc: null
  value: 1
greater_is_better:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
ignore_data_skip:
  desc: null
  value: false
label_names:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
learning_rate:
  desc: null
  value: 0.001
load_best_model_at_end:
  desc: null
  value: true
local_rank:
  desc: null
  value: -1
logging_dir:
  desc: null
  value: runs/Mar05_23-12-10_Zijiao-pc
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
lr_scheduler_type:
  desc: null
  value: linear
max_grad_norm:
  desc: null
  value: 1.0
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: loss
no_cuda:
  desc: null
  value: false
num_train_epochs:
  desc: null
  value: 10
output_dir:
  desc: null
  value: ../results
overwrite_output_dir:
  desc: null
  value: false
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 32
per_device_train_batch_size:
  desc: null
  value: 32
per_gpu_eval_batch_size:
  desc: null
  value: None
per_gpu_train_batch_size:
  desc: null
  value: None
prediction_loss_only:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
report_to:
  desc: null
  value: '[''wandb'']'
run_name:
  desc: null
  value: ../results
save_steps:
  desc: null
  value: 500
save_total_limit:
  desc: null
  value: 1
seed:
  desc: null
  value: 42
sharded_ddp:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: None
train_batch_size:
  desc: null
  value: 32
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
